contact_links:
  - name: 💬 Need Help? Check Our Support Guide!
    url: https://github.com/your-repo/.github/blob/main/SUPPORT.md
    about: Please refer to our support guide before opening an issue.

